### ISSUE TITLE
[FEATURE] 1.20.6 Support

### ISSUE THREAD

**Issue by Manu585** [HibiscusMC/HMCWraps#139]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Please update the plugin to support 1.20.6 and 1.21.
I know you probably have a lot going on and don't always have time to work on the plugin, but it should be possible to at least update the plugin without any features, I know the API changes are kinda big in comparison to the previous ones.

### Config Changes

Just adding the 1.20.6 and 1.21 features

### How significant is the feature?

Moderate - Needs moderate changes to the current structure

**Comment by Skyslycer** [comment]
Update has been published today. Please try it and open another issue on GH/ticket in the Discord server if you notice any problems.
