### ISSUE TITLE
[FEATURE] Support 1.21.3

### ISSUE THREAD

**Issue by dinobossytnew** [HibiscusMC/HMCWraps#147]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

add support 1.21.3

### Config Changes

null

### How significant is the feature?

Moderate - Needs moderate changes to the current structure

**Comment by dinobossytnew** [comment]
https://mclo.gs/M6vGr3F#L1095

**Comment by Skyslycer** [comment]
I don't know why you created this issue... The logs you sent show the plugin enabling just fine. The line you linked shows an error message from the plugin ItemsAdder, **not** HMCWraps. There is nothing I can do to make ItemsAdder support 1.21.3.

**Comment by dinobossytnew** [comment]
revisare esto gracias :D
