### ISSUE TITLE
[FEATURE] Better file structure

### ISSUE THREAD

**Issue by Verdux** [HibiscusMC/HMCWraps#32]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Separate files/folders for wraps configuration. Currently everything is under config.yml which over time will result in thousands of lines being added and making changes/alterations more complicated as time goes on.

Recommended structure

/HMCWraps/Wraps/swords.yml
/HMCWraps/Wraps/pickaxes.yml
etc...

### Config Changes

Remove all wraps from config.yml and into the new file structure as shown above

### How significant is the feature?

Huge - Requires many changes in the current structure

**Comment by lucian929** [comment]
I propose using something similar to HMCCosmetics: Remapped's configuration system.

```

HMCWraps/
├─ wraps/
│  ├─ christmas_wraps.yml
│  ├─ halloween_wraps.yml
```

Users would define as many wraps as they want within a .yml file they create in the `wraps` folder. This not only would resolve the issue, but it would preserve continuity across our "HMC" plugins.

**Comment by Skyslycer** [comment]
What I had in mind is preserving the current idea of mapping materials/collections to a list of wraps, which means that the filename would be the material/collection and it would contain all wraps for the given thing.
This would make it easier to see where you have wraps of what.
Examples:
`STONE_SWORD.yml`, `SWORDS.yml`

**Comment by Fisher2911** [comment]
Those both sound like the same idea right?

**Comment by Skyslycer** [comment]
They are probably the same, in case those file names were collections.

**Comment by lucian929** [comment]
My name idea was just for sorting, but doing it by material/collection would likely work fine too. It might be worth it to ask the beta testers which they would prefer.

**Comment by Skyslycer** [comment]
Sounds good, I'll do a poll.

**Comment by Skyslycer** [comment]
Added in latest push.
