### ISSUE TITLE
[FEATURE] Preserve Original Model Id

### ISSUE THREAD

**Issue by Skyslycer** [HibiscusMC/HMCWraps#33]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Currently, if a player wraps an item and then unwraps it, the plugin sets its model id to the vanilla one, not the one before it was added.
It should save it in PDC and retrieve it once something gets unwrapped.
There should be a default too.

### Config Changes

- Boolean to enable
- List of items/collections with default model id

### How significant is the feature?

Moderate - Needs moderate changes to the current structure

**Comment by iElijahhh** [comment]
save that data, baby

**Comment by Skyslycer** [comment]
Added in latest push.
