### ISSUE TITLE
[FEATURE] Particles/sounds effects

### ISSUE THREAD

**Issue by iElijahhh** [HibiscusMC/HMCWraps#35]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Would be nice to have a customizable particles/sound effects (maybe even our own from a resource pack) for when wraps are applied.

### Config Changes

items:
  IRON_SWORD:
    wraps:
      1:
        permission: 'hmcwraps.silver_sword'
        uuid: 'silver_sword'
        id: '2'
        name: '<aqua>Silver <gray>Wrap'
        lore:
          - '<gray>Apply this wrap to make your sword look silver!'
        flags:
          - 'HIDE_ATTRIBUTES'
          # new options:
        particles: Villager
        particles_style: Sphere
        sound: entity_firework_rocket_blast

### How significant is the feature?

Huge - Requires many changes in the current structure

**Comment by Skyslycer** [comment]
This has been added in #39
