### ISSUE TITLE
[FEATURE] Custom Armor Support

### ISSUE THREAD

**Issue by TwistedDreams** [HibiscusMC/HMCWraps#36]
### I have checked that...

- [x] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Wraps currently supports CustomModelData, but not dyed leather (required for custom armors) this suggestion is for the config to include an RGB option, as well as a model ID, this would then directly add support for Custom Armors using fancypants core shaders, Oraxen or ItemsAdder.

### Config Changes

custom-armor-example:
        permission: 'hmcwraps.custom_armor'
        uuid: 'custom_armor_example'
        id: '1'
        **rgb: '38, 192, 210'** #NEW CONFIG OPTION EXAMPLE
        name: '<white>Custom Armor'
        locked-name: '<red>Locked!'
        lore:
          - '<gray>Apply this wrap to your item'
        locked-lore:
          - '<gray>You need to buy this item in our <red>store<gray>!'
        glow: true
        flags:
          - 'HIDE_ATTRIBUTES'

### How significant is the feature?

Meerly Significant - Small feature fitting perfectly into the current structure

**Comment by Skyslycer** [comment]
I'm going to have to add RGB preservation method, aren't I? (btw it doesn't fit into the current structure as everything is around CMD, so it'd be mega huge)
But this could be done, I may consider it for next week.

**Comment by Skyslycer** [comment]
I have approved this issue as you're one of the main guys in the wrap plugin industry which means, I owe you.
And after considering, it's still gonna be a hell lot of work but it sounds useful :D

**Comment by Skyslycer** [comment]
[ ] Add config option
[ ] Check if is Leather or sth still gotta figure out
[ ] Implement in setWrap
[ ] RGB preservation

**Comment by Skyslycer** [comment]
Should have been added with 9ea4da5, not tested yet, but we'll get everything working ASAP.
