### ISSUE TITLE
[FEATURE] Further permission-setting options?

### ISSUE THREAD

**Issue by detoxv** [HibiscusMC/HMCWraps#56]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Would it be possible to add any extra permission-settings on top of the existing ones? Currently, even with all checks enabled users who do not have permission to use / own wrapped items can still pick up and equip them in-hand, store within an enderchest, etc.

These items only become unwrapped upon using them via clicking or opening the /wraps inventory which is great, but in my case I want to make rare wraps and have specific use cases, it would be ideal if they could be more strictly permission locked to individual players.

I am not sure if these options would be optimized or the best solution:
check upon opening the in-game inventory or containers like chests?
check permissions upon dropped item pickup?

### Config Changes

e.g 

permission-settings:
  inventory-open-permission: true
  item-pickup-permission: true

### How significant is the feature?

Meerly Significant - Small feature fitting perfectly into the current structure

**Comment by Skyslycer** [comment]
Currently, the pickup check is implemented and working (haven't tested it in a while though), but I'll add the check when opening an inventory.
There are some bugs I'll have to resolve first including the pickup check if that is not working.

**Comment by detoxv** [comment]
Oh, my bad, I just realised that the item pickup check was user error on my part. It is working fine, I just tested it now.

I suppose the inventory check could be a good solution as the only remaining scenario that I can see is taking a wrapped item out of a chest allows it to go into the users inventory and be kept.

Thank you for your quick reply and excellent work on this plugin!

**Comment by Skyslycer** [comment]
Awesome, I'll add that feature soon! Thanks for the issue on GitHub, it helps track features and bugs better.
Have fun with the plugin!

**Comment by Skyslycer** [comment]
Has been added and will be committed soon!
