### ISSUE TITLE
[FEATURE] Allow nameless items like "AIR" in the GUI - Invisible items with no name

### ISSUE THREAD

**Issue by mkhansen981017** [HibiscusMC/HMCWraps#59]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Allow the item material "AIR" in the GUI config file setup. Either that or any other alternative would allow users to set an invisible item with no name.

This would allow users to display custom art over the GUI itself.
example here: https://imgur.com/a/qKyQIm6
In the image from the link, my mouse cursor is placed directly above the "hammer" icon. No text for an item name is shown here

Also not sure of what to list this as in the "How significant is the feature". I've chosen to list it as "Meerly Significant"

### Config Changes

Anything that would mean the above is possible

### How significant is the feature?

Meerly Significant - Small feature fitting perfectly into the current structure

**Comment by Skyslycer** [comment]
You can just add a model id to paper with an empty texture as far as I am aware. So where exactly do you want items to be air/nothing? The wraps in the inventory or the items in the inventory?

**Comment by Skyslycer** [comment]
This should just be a filler or nothing item so no wraps get placed there.

**Comment by Skyslycer** [comment]
Has been added, will be released in 1.2.1 soon.
