### ISSUE TITLE
[FEATURE] <MMOITEMS & ITEMSADDERS>

### ISSUE THREAD

**Issue by dinobossytnew** [HibiscusMC/HMCWraps#60]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

It would be nice to have support for mmoitems and executableitems so that the effects of these items are not erased.

### Config Changes

No configuration is needed, just apply it like any other item and that's it.

### How significant is the feature?

Meerly Significant - Small feature fitting perfectly into the current structure

**Comment by Skyslycer** [comment]
Do you have Discord by any chance?

**Comment by dinobossytnew** [comment]
> ¿Tienes Discord por casualidad?

DinoBoss#6985

**Comment by dinobossytnew** [comment]
Also to support trusses and layers of the same trusses x parts.

**Comment by Skyslycer** [comment]
What does that mean? And I have tried both plugins and not any of them seam to loose abilities when applying wraps.

**Comment by dinobossytnew** [comment]
> Refe

If I saw what happened, I had not said it but it is the mmoitems that had the debug activated wrong.

**Comment by Skyslycer** [comment]
Can't confirm. Issue has been in limbo for quite a while now.
