### ISSUE TITLE
[FEATURE] Add support for MythicMobs items

### ISSUE THREAD

**Issue by lucian929** [HibiscusMC/HMCWraps#63]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Add support for MythicMobs, similar to the Oraxen & ItemsAdder hook.

This is already a feature in [HMCCosmetics](https://github.com/HibiscusMC/HMCCosmetics/search?q=mythicmobs), so it makes sense to add here, plus may be useful for users who use MythicMobs + Crucible to manage their custom tools.

### Config Changes

support for:

`id: mythicmobs: <item_name>`

### How significant is the feature?

Meerly Significant - Small feature fitting perfectly into the current structure

**Comment by Skyslycer** [comment]
Added!
