### ISSUE TITLE
[FEATURE] Make locked-lore and locked-name not depend on eachother

### ISSUE THREAD

**Issue by lucian929** [HibiscusMC/HMCWraps#64]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

When adding a wrap, if you add the `locked-name` key without adding `locked-lore`, it will produce an NPE regarding no locked lore.

Doing the opposite (adding `locked-lore` without `locked-name`) produces no error, but the locked lore will not be displayed, regardless of if the user has the permission or not.

The plugin should allow users to either have locked-name, locked-lore, or both.

### Config Changes

n/a

### How significant is the feature?

Meerly Significant - Small feature fitting perfectly into the current structure

**Comment by lucian929** [comment]
I'm not sure if I should have categorized this as a bug or a feature so I put it as feature for now.

**Comment by Skyslycer** [comment]
Fixed
