### ISSUE TITLE
[FEATURE] Random

### ISSUE THREAD

**Issue by BendersRepublic** [HibiscusMC/HMCWraps#78]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

can you add a random command? like wraps give wrapper <type/all> random or even a placeholder that displays a different wrap each time it's processed. This way I can easily create a randomizer myself

### Config Changes

N/A

### How significant is the feature?

Meerly Significant - Small feature fitting perfectly into the current structure

**Comment by Skyslycer** [comment]
This can be easily made with the wraps API, since I think it would be a very niche addition.
If you have any questions regarding the API, just message me on Discord :D
