### ISSUE TITLE
[FEATURE] Add ingame Model

### ISSUE THREAD

**Issue by dinobossytnew** [HibiscusMC/HMCWraps#84]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

The function consists in adding a new command that allows to easily add models to the hmcwraps plugin from minecraft connected 1 player.

But how does it work?

Using 1 command like /hmcwraps savemodel <args[1].modelname> <args[2].itemsadder/oraxen> <args[3].category item> <args[4].id> 

With the command you need to have the item in hand this may shorten the command as the plugin will know if the datonbt is from ia or oraxen this I wouldn't know yet I didn't see the code itself to see if it could be made easy or hard enough.

### Config Changes

The configuration will not change and you will be able to keep the path perfectly.

### How significant is the feature?

Moderate - Needs moderate changes to the current structure

**Comment by dinobossytnew** [comment]
**is possible?**

**Comment by Skyslycer** [comment]
Hi, I'm quite unsure of what you mean, could explain it in a little bit more detail?

**Comment by dinobossytnew** [comment]
> Hi, I'm quite unsure of what you mean, could explain it in a little bit more detail?

1 command to add the model with the material in the configuration.
I just place the command with the item in hand and the model is added to the configuration.

**Comment by Skyslycer** [comment]
Maybe there will be a visual editor, but just a command on its own is not planned, as it doesn't seem like a big hassle to add a few lines to a config.
Thank you for your suggestion though!
